name: mosaico
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  syncfusion_flutter_calendar: ^22.1.37
  flutter_launcher_icons: ^0.13.1
  graphic: ^2.2.0
  intl: ^0.18.1
  url_launcher: ^6.1.12
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/logo.jpg"  

flutter:
  uses-material-design: true
  assets:
    - assets/
  
  

 
